/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack.view;
import java.io.File;
import java.text.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import pack.control.controllerHitung;

/**
 *
 * @author Enggar R S
 */
public class Hitung_Gaji extends javax.swing.JFrame {
    controllerHitung chitung;

    /**
     * Creates new form Hitung_Gaji
     */
    public Hitung_Gaji() {
       chitung = new controllerHitung(this);
        chitung.isiTable();
        String user = null;
        txtNama.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        combo_bulan = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtstruktural = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtkeluarga = new javax.swing.JTextField();
        txtanak = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtTgl = new javax.swing.JTextField();
        txtjml_anak = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtpokok = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        bEdit = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1Data = new javax.swing.JTable();
        bSave = new javax.swing.JButton();
        bClean = new javax.swing.JButton();
        bDelete2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(0, 51, 255));
        jPanel6.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("FORM TRANSAKSI");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(182, 0, 297, 45);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 51));
        jLabel18.setText("Total Gaji Bersih :");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(500, 350, 160, 17);

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("HITUNG GAJI PEGAWAI");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(182, 40, 290, 31);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel2.setText("NIP");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 100, 14);

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);
        jPanel5.add(jTextField2);
        jTextField2.setBounds(157, 14, 169, 20);

        jComboBox2.setEditable(true);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox2);
        jComboBox2.setBounds(157, 44, 190, 20);

        jLabel27.setText("NIP");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(13, 47, 100, 14);

        jLabel28.setText("Nomor Slip");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(13, 17, 100, 14);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(2, 180, 0, 0);
        jPanel1.add(txtNip);
        txtNip.setBounds(160, 10, 180, 20);

        combo_bulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Pebruari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "Nopember", "Desember" }));
        jPanel1.add(combo_bulan);
        combo_bulan.setBounds(160, 40, 170, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Untuk Gaji Bulan   :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 40, 117, 17);

        jPanel6.add(jPanel1);
        jPanel1.setBounds(10, 100, 360, 78);

        jLabel22.setForeground(new java.awt.Color(255, 255, 51));
        jLabel22.setText("Jabatan   :");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(480, 90, 52, 30);

        jLabel23.setForeground(new java.awt.Color(255, 255, 51));
        jLabel23.setText("CXC");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(550, 90, 90, 30);

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        txtstruktural.setText("0");
        txtstruktural.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstrukturalActionPerformed(evt);
            }
        });
        jPanel3.add(txtstruktural);
        txtstruktural.setBounds(190, 50, 203, 30);

        jLabel11.setText(" Anak  (Rp)");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 140, 164, 14);

        jLabel12.setText("Keluarga (Suami/istri)  (Rp)");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 90, 164, 20);

        txtkeluarga.setText("0");
        jPanel3.add(txtkeluarga);
        txtkeluarga.setBounds(190, 90, 203, 30);

        txtanak.setText("0");
        txtanak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanakActionPerformed(evt);
            }
        });
        jPanel3.add(txtanak);
        txtanak.setBounds(190, 130, 203, 30);

        jLabel13.setText("Jabatan Struktural  (Rp)");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(13, 58, 164, 14);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(13, 39, 394, 10);

        jLabel37.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel37.setText("B. TUNJANGAN");
        jPanel3.add(jLabel37);
        jLabel37.setBounds(13, 3, 239, 19);

        jPanel6.add(jPanel3);
        jPanel3.setBounds(480, 130, 420, 170);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setEnabled(false);
        jPanel2.setLayout(null);

        jLabel4.setText("Nama Pegawai");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(13, 64, 126, 14);

        jLabel5.setText("Golongan");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(13, 126, 134, 14);

        jLabel6.setText("Status");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(13, 157, 134, 14);

        jLabel7.setText("Jumlah Anak");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(13, 180, 77, 14);

        jLabel8.setText("Gaji Pokok (Rp.)");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(13, 211, 121, 14);

        jTextField3.setEditable(false);
        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(jTextField3);
        jTextField3.setBounds(151, 61, 186, 20);

        jTextField4.setEditable(false);
        jTextField4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(jTextField4);
        jTextField4.setBounds(151, 92, 186, 20);

        jTextField5.setEditable(false);
        jTextField5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(jTextField5);
        jTextField5.setBounds(151, 154, 186, 20);

        jTextField6.setEditable(false);
        jTextField6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(jTextField6);
        jTextField6.setBounds(151, 180, 186, 20);

        jTextField7.setEditable(false);
        jTextField7.setText("0");
        jTextField7.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(jTextField7);
        jTextField7.setBounds(151, 211, 186, 20);

        jTextField12.setEditable(false);
        jTextField12.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel2.add(jTextField12);
        jTextField12.setBounds(151, 123, 186, 20);

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(13, 44, 321, 11);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setText("A. GAJI POKOK");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(13, 14, 378, 19);

        jLabel15.setText("Tanggal Lahir");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(13, 95, 134, 14);

        jPanel6.add(jPanel2);
        jPanel2.setBounds(2, 270, 360, 0);

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jLabel1.setText("Nama Pegawai");
        jPanel8.add(jLabel1);
        jLabel1.setBounds(10, 40, 100, 14);

        jLabel30.setText("Nama Pegawai");
        jPanel8.add(jLabel30);
        jLabel30.setBounds(13, 17, 100, 14);

        jPanel6.add(jPanel8);
        jPanel8.setBounds(10, 280, 360, 0);

        jPanel7.setBackground(new java.awt.Color(0, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setText("Nama Pegawai");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 100, -1));
        jPanel7.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, -1));

        jLabel33.setText("Tanggal Lahir");
        jPanel7.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, -1));

        jLabel35.setText("Gaji Pokok");
        jPanel7.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 100, 20));

        jLabel36.setText("Status");
        jPanel7.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setText("A.GAJI POKOK");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 239, -1));

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel7.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 170, -1));

        txtTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTglActionPerformed(evt);
            }
        });
        jPanel7.add(txtTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 170, -1));
        jPanel7.add(txtjml_anak, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 170, -1));

        jLabel38.setText("Jumlah Anak");
        jPanel7.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 20));
        jPanel7.add(txtpokok, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 170, -1));

        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });
        jPanel7.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 170, -1));

        jPanel6.add(jPanel7);
        jPanel7.setBounds(10, 190, 360, 220);

        txttotal.setEditable(false);
        txttotal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txttotal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jPanel6.add(txttotal);
        txttotal.setBounds(700, 330, 170, 40);

        bEdit.setBackground(new java.awt.Color(0, 255, 255));
        bEdit.setFont(new java.awt.Font("Tekton Pro Ext", 1, 15)); // NOI18N
        bEdit.setText("U B A H");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        jPanel6.add(bEdit);
        bEdit.setBounds(640, 420, 270, 40);

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));
        jPanel4.setForeground(new java.awt.Color(0, 51, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb1Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "bulan_gaji", "nip", "nama_pegawai", "tgl_lahir", "status", "jumlah_anak", "gaji_pokok", "jabatan_struktural", "keluarga", "anak", "total_gaji"
            }
        ));
        jScrollPane1.setViewportView(tb1Data);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 25, 850, 200));

        jPanel6.add(jPanel4);
        jPanel4.setBounds(30, 470, 890, 250);

        bSave.setBackground(new java.awt.Color(0, 255, 255));
        bSave.setFont(new java.awt.Font("Tekton Pro Ext", 1, 15)); // NOI18N
        bSave.setText("S I M P A N");
        bSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveActionPerformed(evt);
            }
        });
        jPanel6.add(bSave);
        bSave.setBounds(50, 420, 270, 40);

        bClean.setBackground(new java.awt.Color(0, 255, 255));
        bClean.setFont(new java.awt.Font("Tekton Pro Ext", 1, 15)); // NOI18N
        bClean.setText("B E R S I H");
        bClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCleanActionPerformed(evt);
            }
        });
        jPanel6.add(bClean);
        bClean.setBounds(360, 740, 270, 40);

        bDelete2.setBackground(new java.awt.Color(0, 255, 255));
        bDelete2.setFont(new java.awt.Font("Tekton Pro Ext", 1, 15)); // NOI18N
        bDelete2.setText("H A P U S");
        bDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDelete2ActionPerformed(evt);
            }
        });
        jPanel6.add(bDelete2);
        bDelete2.setBounds(350, 420, 270, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTglActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void bSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveActionPerformed
          chitung.SimpanData();
          chitung.isiTable();
    }//GEN-LAST:event_bSaveActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
         chitung.Ubah();
        chitung.isiTable();
    }//GEN-LAST:event_bEditActionPerformed

    private void txtstrukturalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstrukturalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstrukturalActionPerformed

    private void txtanakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanakActionPerformed

    private void bDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDelete2ActionPerformed
         chitung.Hapus();
        chitung.isiTable();
    }//GEN-LAST:event_bDelete2ActionPerformed
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        // TODO add your handling code here:
        String Halouser = Login.useraktif;
        txtNama.setText(Halouser);
    }  
     private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        int baris = getTableData().getSelectedRow();
        if(baris != -1){
            combo_bulan.setSelectedItem(getTableData().getValueAt(baris, 0).toString());
            txtNip.setText((String) getTableData().getValueAt(baris, 1));
            txtNama.setText(getTableData().getValueAt(baris, 2).toString());
            txtTgl.setText(getTableData().getValueAt(baris, 3).toString());
            txtStatus.setText(getTableData().getValueAt(baris, 4).toString());
            txtjml_anak.setText(getTableData().getValueAt(baris, 5).toString());
            txtpokok.setText(getTableData().getValueAt(baris, 6).toString());
            txtstruktural.setText(getTableData().getValueAt(baris, 7).toString());
            txtkeluarga.setText(getTableData().getValueAt(baris, 8).toString());
            txtanak.setText(getTableData().getValueAt(baris, 9).toString());
            txttotal.setText(getTableData().getValueAt(baris, 10).toString());
        }
    }                                    

    
    private void bCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCleanActionPerformed
        chitung.Reset();
    }//GEN-LAST:event_bCleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hitung_Gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hitung_Gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hitung_Gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hitung_Gaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClean;
    private javax.swing.JButton bDelete2;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bSave;
    private javax.swing.JComboBox combo_bulan;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTable tb1Data;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTgl;
    private javax.swing.JTextField txtanak;
    private javax.swing.JTextField txtjml_anak;
    private javax.swing.JTextField txtkeluarga;
    private javax.swing.JTextField txtpokok;
    private javax.swing.JTextField txtstruktural;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

    
   public JTextField getTxtNip() {
        //To change body of generated methods, choose Tools | Templates.
         return txtNip;
    }

    public JTextField getTxtNama() {
        //To change body of generated methods, choose Tools | Templates.
         return txtNama;
    }

    public JTextField getTxtTgl() {
        //To change body of generated methods, choose Tools | Templates.
         return txtTgl;
    }

    public JComboBox getCbBulan() {
        //To change body of generated methods, choose Tools | Templates.
         return combo_bulan;
    }

    public JTextField getTxtStatus() {
        //To change body of generated methods, choose Tools | Templates.
         return txtStatus;
    }
     public JTextField getTxtJml_anak() {
        //To change body of generated methods, choose Tools | Templates.
         return txtjml_anak;
    }
    public JTextField getTxtPokok(){  
        return txtpokok;    
    }   
    
     public JTextField getTxtStruktural(){  
        return txtstruktural;    
    }  
     public JTextField getTxtKeluarga(){  
        return txtkeluarga;    
    }  
     public JTextField getTxtAnak(){  
        return txtanak;    
    }  
      public JTextField getTxtTotal(){  
        return txttotal;    
    }  
    public JButton getButtonHapus(){   
        return bDelete2;   
    }   
    
    public JButton getButtonBersih(){  
        return bClean;  
    }   
    
    public JButton getButtonSimpan(){ 
        return bSave;   
    }  
    
    public JButton getButtonUbah(){  
        return bEdit; 
    }    
      
    
    public JTable getTableData(){     
        return tb1Data;  
    }

}
